spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
