spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/ridao/IdeaProjects/spring-cloud-course/git-localconfig-repo
server:
  port:
    8888